version: "3.9"
services:
  postgres:
    image: postgres:14.5
    build:
      context: ""
      dockerfile: dockerFile
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123qwedsazxcVBN"
    ports:
      - "5432:5432"