# Generated by Django 4.1.1 on 2022-09-11 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('parentId', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(choices=[(1, 'FILE'), (2, 'FOLDER')], max_length=64)),
                ('size', models.IntegerField(blank=True)),
                ('childrenId', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, size=None)),
            ],
            options={
                'db_table': 'SystemItem',
            },
        ),
        migrations.CreateModel(
            name='SystemItemImport',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=128)),
                ('parentId', models.CharField(blank=True, max_length=64)),
                ('childrenId', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[(1, 'FILE'), (2, 'FOLDER')], max_length=64)),
                ('size', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Документы',
                'db_table': 'SystemItemImport',
            },
        ),
    ]
