# Generated by Django 4.1.1 on 2022-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemitem',
            name='type',
            field=models.CharField(choices=[('FILE', 'File'), ('FOLDER', 'Folder')], max_length=64),
        ),
    ]
