# Generated by Django 4.1.1 on 2022-09-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_systemitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemitem',
            name='date',
            field=models.CharField(max_length=64),
        ),
    ]
