# Generated by Django 4.1.1 on 2022-09-11 10:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_systemitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemitem',
            name='childrenId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, null=True, size=None),
        ),
    ]
