# Generated by Django 4.1.1 on 2022-09-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_systemitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemitem',
            name='date',
        ),
    ]
