# Generated by Django 4.1.1 on 2022-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_remove_systemitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemitem',
            name='date',
            field=models.CharField(default='2022-05-28T21:12:01.000Z', max_length=128),
            preserve_default=False,
        ),
    ]
