# Generated by Django 4.1.1 on 2022-09-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_systemitem_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemitem',
            old_name='date',
            new_name='dateTime',
        ),
    ]
