# Generated by Django 4.1.1 on 2022-09-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_rename_date_systemitem_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemitem',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemitem',
            name='url',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
