# Generated by Django 4.1.1 on 2022-09-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_systemitem_size_alter_systemitem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemitem',
            old_name='dateTime',
            new_name='date',
        ),
    ]
