# Generated by Django 4.1.1 on 2022-09-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_rename_datetime_systemitem_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemItemImport',
        ),
        migrations.RemoveField(
            model_name='systemitem',
            name='childrenId',
        ),
    ]
