# Generated by Django 4.1.1 on 2022-09-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_delete_systemitemimport_remove_systemitem_childrenid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemItem',
            new_name='Item',
        ),
    ]
